[tool.poetry]
name = "fizzbuzz"
version = "0.1.0"
description = ""
authors = ["Pablo <pablo.tejgar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

